version: '3'
services:
  web:
    image:  kunalk07/docker-jenkins-cicd:1.4
    ports:
      - "5000:5000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: ec2-tutorial
        awslogs-region: ap-south-1
        awslogs-stream-prefix: web
